Add support for Tales of Xillia
isJuhn/KAMI pull request #20
Opened 2021-04-29 16:44 UTC by AphelionWasTaken

Adds support for the NA PSN version of Tales of Xillia.

Sorry for the mess to squash... I will make sure to keep things clean in the future.

2021-04-29 17:51 UTC, isJuhn commented on Xillia1.cs
> +}
missing newline

2021-04-30 14:46 UTC, n-laszlo-m requested changes
Could you also add the game to the README.md compat list (following the already present format)? And maybe also fix the typo I made there with `Ratched & Clank: Tools of Destruction`? :P

2021-04-30 14:46 UTC, n-laszlo-m commented on Xillia1.cs
> +
please remove this empty line

2021-04-30 14:46 UTC, n-laszlo-m commented on Xillia1.cs
> +            IPCUtils.WriteFloat(m_ipc, (uint)m_vert.Value, m_camera.Vert);
please indent this

2021-04-30 14:46 UTC, n-laszlo-m commented on Xillia1.cs
> +
please remove newline here as well

2021-04-30 15:01 UTC, dio-gh requested changes
Looks pretty solid! Could you please also adjust readme.md and add the game to the quasi-compatlist following the format already laid out? Also, could you please fix my typo in r&c:tod while there? 😅 Accidentally wrote Ratched instead of Ratchet.

2021-04-30 16:19 UTC, dio-gh approved these changes
LGTM!

2021-05-03 08:11 UTC, isJuhn commented on KAMI/Games/Xillia1.cs
> +        DerefChain m_vert;
You can use a single `DerefChain` and then when reading do
```
                m_camera.Hor = IPCUtils.ReadFloat(m_ipc, (uint)m_addr.Value);
                m_camera.Vert = IPCUtils.ReadFloat(m_ipc, (uint)(m_addr.Value + 4));
```

2021-05-03 08:12 UTC, isJuhn commented on KAMI/Games/Xillia1.cs
> +                m_camera.Vert = (float)(IPCUtils.ReadFloat(m_ipc, (uint)m_vert.Value));
redundant cast to float

2021-05-04 15:56 UTC, merged

2021-06-02 15:13 UTC, aaaaadox reviewed
hm