Add support for Bad Company, update pine to latest upstream
isJuhn/KAMI pull request #62
Opened 2022-07-16 01:46 UTC by isJuhn

Not sure if the tracing is fully correct, but it seems stable from what I've tested. This is only for EU 1.20 right now

2022-07-18 10:28 UTC, dio-gh requested changes
LGTM other than some minor nitpicks :+1:

2022-07-18 10:28 UTC, dio-gh commented on KAMI.Core/GameManager.cs
> +                case "BLUS30118":  return new BattlefieldBadCompany(ipc, id);
nit: formatting (there's double space before the return)

2022-07-18 10:28 UTC, dio-gh commented on KAMI.Core/Games/BattlefieldBadCompany.cs
> +            int baseAddress = serialId == "BLES00261" ? 0x15A5A88 : 0x15BFF28;
This seems a bit too optimistic, might worth throwing in a C# 8.0 switch expression like I did in my [RDR hook](https://github.com/isJuhn/KAMI/blob/master/KAMI.Core/Games/RedDeadRedemption.cs#L13-L25) to make it more explicit and better looking.

2022-07-18 10:28 UTC, dio-gh commented on KAMI.Core/Games/BattlefieldBadCompany.cs
> +            m_addr = DerefChain.CreateDerefChain(ipc, baseAddress, 0x1c, 0x1c0, 0x14, 0x2c, 0x4, 0x4, 0x8, 0x4, 0x1bc, 0x20c, 0x3c, 0x8, 0x8);
Do you think we could figure out a coding guideline for the formatting of these? I'm not *super* tight about keeping things under 80 or 100 columns, but it could be nice. Especially cause in the hook implementation phase people are basically just plumbing, so SBS views are likely.

2022-12-01 19:39 UTC, isJuhn commented on KAMI.Core/Games/BattlefieldBadCompany.cs
> +            m_addr = DerefChain.CreateDerefChain(ipc, baseAddress, 0x1c, 0x1c0, 0x14, 0x2c, 0x4, 0x4, 0x8, 0x4, 0x1bc, 0x20c, 0x3c, 0x8, 0x8);
maybe later, and get some auto-formater

2022-12-01 19:40 UTC, isJuhn commented on KAMI.Core/Games/BattlefieldBadCompany.cs
> +            int baseAddress = serialId == "BLES00261" ? 0x15A5A88 : 0x15BFF28;
I'll leave it until I decide to pick up BF:BC again

2022-12-01 19:40 UTC, isJuhn commented
gonna merge this as is, it's incomplete but it's a start. Might pick it back up later when I feel like reversing again

2022-12-01 19:41 UTC, merged