Implement DerefChain
isJuhn/KAMI pull request #7
Opened 2021-03-19 19:09 UTC by isJuhn

Could use some love still, but this should be a good starting point. And it should free unblock #2.

2021-03-19 19:20 UTC, dio-gh requested changes

2021-03-19 19:20 UTC, dio-gh commented on KAMI/Games/Killzone1PS3.cs
> +            DerefChain.VerifyChains(m_hor, m_vert);
As discussed on GitHub, this should return `false` if a recalc was attempted and failed, and `true` otherwise. This would be to guard the following statements by putting the call into an if prior to them. Currently this would bail on P5 due to the game changing the base pointer to `nullptr` during cutscenes and loading screens.

2021-03-19 19:20 UTC, dio-gh commented on KAMI/Cameras/HVecVACamera.cs
> +            double horAngle = Math.Atan2(HorY, HorX);
Why was this swapped around?

2021-03-19 19:32 UTC, isJuhn commented on KAMI/Cameras/HVecVACamera.cs
> +            double horAngle = Math.Atan2(HorY, HorX);
I memed it up before, now that I tested killzone again it was broken somewhat, if you look in killzone file you'll see that m_camera.HorX and HorY are swapped around there too.

2021-03-21 18:19 UTC, isJuhn commented on KAMI/Games/Killzone1PS3.cs
> +            DerefChain.VerifyChains(m_hor, m_vert);
fixd

2021-03-21 20:02 UTC, dio-gh approved these changes

2021-03-21 20:05 UTC, merged